### ISSUE TITLE
Redis search stuck at loading

### ISSUE THREAD

**Issue by urossmolnik** [TeamSQL/desktop-app#147]
Redis search is not finding all the keys for me - sometimes stuck at loading.  
Executing `KEYS` command for the same pattern returns results.  

Database has less than 100000 keys.  
Is there a problem if first scan returns no results?

**Comment by erenbaydemir** [comment]
Hi @urossmolnik, 

Actually we didn't want to put a 'SEARCH' placeholder inside that filter box since we're using Redis's SCAN command with a match parameter and SCAN doesn't guarantee to find all matching keys in the first iteration. As you hit Load More, it should keep finding the match results. 

In the next releases, we are planing to do a workaround using an automated iteration with SCAN command or just using other commands like KEYS to find the appropriate keys without paging. 

Is that the case that you're experiencing or do you think something else is wrong?

Thank you.
