### ISSUE TITLE
Can't Edit Inline Serialized Columns Values

### ISSUE THREAD

**Issue by Zaifor** [TeamSQL/desktop-app#217]
OS: Mac OS High Siera - 10.13.3 - x64
VERSION: 3.2.187
---------------
Database Type: MySQL 5.6
How can this issue be reproduced?

![image](https://user-images.githubusercontent.com/2466340/37912718-c0c70ab4-311b-11e8-888b-b7c60023a1d0.png)

### Can't edit inline serialized columns/values. 

Let's say we have a column **values**. The content under that column is serialized and when you try to edit the column's cell the content it's displayed as one line. Pressing the apply button throws the above error.

Expected format
```
--- 
:created_at: true
:name: true
```

Actual format
```
--- :created_at: true:name: true
```

Result:
```
ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'values = '--- :created_at: true:name: true'
```

**Comment by abacigil** [comment]
Hi @Zaifor 

You got syntax error because "values" keyword is a reserved keyword. If you/we don't use backtick (`) for column, tables or other database items in MySQL, the server will throw syntax error. Same for other databases also.

We already prepared a hotfix for today and the problem will be fixed.

Thanks,
