### ISSUE TITLE
Numeric type is displaying rounded as an integer

### ISSUE THREAD

**Issue by jonjonw** [TeamSQL/desktop-app#250]
Numeric type is displaying rounded as an integer.

OS: Linux x64 4.15.18-1-ck-skylake
VERSION: 3.3.201
---------------
Database Type: postgresql
How can this issue be reproduced?

`
create table test(n numeric);
insert into test(n) values (3.14), (2.17);
select n from test;
`
You will see 3 and 2 rather than 3.14 and 2.17.

**Comment by daveburr** [comment]
I also found in my queries that fields containing integer values, when divided by floating point constants, (e.g. SUM (mywork.minutes) / 60.0 ) AS Hours ) are being returned as integers rather than floating point values. This just made TeamSQL unusable for me.  I am running TeamSQL Version 3.3.201 on a Mac, accessing a Redshift database.

**Comment by murteza** [comment]
Hi @daveburr ,

Our technical team are working on your issue too. 
Thank you for reaching us.

**Comment by abacigil** [comment]
Hi there,

We released a new version yesterday, the update will be available soon for all users, instead of waiting for it, you can download the latest version from our website.

Thanks.

**Comment by daveburr** [comment]
Fantastic! Thanks for addressing this issue in such a timely manner. I'll
check it out later this morning.

Dave

**Comment by abacigil** [comment]
By the way,

That query will not return decimal part of numbers, since there is no decimal storage is defined in create table query.

You should create a table like;

`create table test(n numeric(5,2)); insert into test(n) values (3.14), (2.17); select n from test;`

Please check: https://dev.mysql.com/doc/refman/5.5/en/fixed-point-types.html

**Comment by abacigil** [comment]
The update covers similar bugs in Redshift and PostgreSQL, but your case is not a bug of TeamSQL.

Thanks,

**Comment by abacigil** [comment]
Hi @daveburr ,

We've checked your case and latest version fixes the issue, please update to 3.3.203 , thanks.
