### ISSUE TITLE
Logs directory uses up too much disk space

### ISSUE THREAD

**Issue by revbingo** [TeamSQL/desktop-app#315]
After a couple of months of usage, the AppCache/users/*/logs directory is now close to 5GB. It's mostly an issue because I only have a 128GB disk in my MacBook and I'm constantly sailing close to the wind, so I appreciate 5GB likely isn't a problem for a lot of people.

However, as far as I can see, that directory is basically storing the results of every query I've run for the last 2 months, long after that data is useful to me and certainly long after I can access that data via the UI i.e. I have closed the tab (and assumed that the query history is consigned to the trash). 

My expectation is that query/result history would be deleted when the tab is closed.  Or at least the data could be stored compressed on disk (the 4.9GB directory zips to just over 200M)

**Comment by erenbaydemir** [comment]
Hi @revbingo , 

The fix for this will be included in TeamSQL 4 (which is in beta right now). Those cached results will be compressed and you will be able to set the maximum cache size, so the old results ones will automatically be deleted. 

We're keeping cached results even if you close the tabs because we show the cached result sets on the History screen too, where you can click on the query history records of the tabs which you might have closed a long time ago. 

Thank you.

**Comment by selcukkiziltug** [comment]
Hi @revbingo, we fixed this issue on the beta version of TeamSQL 4 which will be released soon. Please get it at [http://teamsql.io/nightly](http://teamsql.io/nightly).
