### ISSUE TITLE
New UI is terrible. Please bring back option for queries on left.

### ISSUE THREAD

**Issue by jimstjean** [TeamSQL/desktop-app#431]
I upgraded to version 4 and wish I didn't. The new UI is very hard to use.

The left column is good for long lists. Tabs on the top are good for short lists.

well I have 20 times more queries than databases. Queries are the long list and should be on the left. Databases are the short list and should be on top. Now I have tons of wasted screen space on the left - my one database, and a very difficult to navigate tab/hamburger menu on top that is awful. I can't even read my query names (which are long) without hovering over them in the hamburger menu.

Seriously this is terrible. I was liking the tool but this was a very bad change.

Tomorrow I am going to dump v4 and try to go back. If I can't, I am going to find another tool

**Comment by selcukkiziltug** [comment]
Hi @jimstjean, thanks for your kind feedback. We redesigned the UI in a result of our user's feedback. We know it's hard to fulfill all of our users needs but we work hard to do it so. You can download the previous versions and go back to the old design at https://teamsql.io/archived-versions.

**Comment by carolineware** [comment]
I hate to say it because I'm trying to convert my whole office to TeamSQL, but I totally agree about the decrease in usability. I have 15 connections and usually 10-15 open tabs. Not to mention that v4 has a known issue that won't let us connect to any DB at all. Thanks very much for the archive! Now we can train our new developers a lot easier and get them started with real work.

**Comment by df-karuna** [comment]
I strongly agree with jimstjean. New UI is too bad to seperate queries by purpose.
